import {filterCatalog} from './core.mjs';
const $=id=>document.getElementById(id);
const samples=[['Neon Velocity','Racing',1998,'PlayStation','#ba346f'],['Moonlight Odyssey','Role-playing',1995,'Super Nintendo','#6956cc'],['Circuit Breakers','Action',2001,'Dreamcast','#258f9a'],['Castle of Echoes','Adventure',1989,'NES','#a5682b'],['Orbit Rivals','Fighting',1997,'Sega Saturn','#385db9'],['Pixel Pioneers','Platformer',2004,'GameCube','#428946']].map(([title,genre,year,console,color],i)=>({id:`sample-${i}`,title,genre,year,console,color,rating:'Unverified',sample:true}));
let items=[],stash=[];
try{const stored=JSON.parse(localStorage.getItem('savepoint-stash')||'[]');if(Array.isArray(stored))stash=stored.filter(x=>typeof x==='string')}catch{}
try{const r=await fetch('./catalog.json');if(!r.ok)throw Error('Catalog unavailable');items=await r.json();if(!Array.isArray(items))throw Error('Invalid catalog');if(items.length===0)items=samples;else document.querySelector('.notice').textContent='Catalog preview · Availability and prices require seller confirmation. No live orders.';}catch{items=samples;document.querySelector('.notice').textContent='The catalog could not be loaded. Showing fictional samples only; nothing here is offered for sale.'}
stash=stash.filter(id=>items.some(x=>x.id===id));
for(const field of ['genre','decade','console','rating']){const values=[...new Set(items.map(x=>field==='decade'?Math.floor(x.year/10)*10:x[field]).filter(Boolean))].sort();for(const v of values){const o=document.createElement('option');o.value=v;o.textContent=field==='decade'?`${v}s`:v;$(field).append(o)}}
let letter='';
for(const value of ['ALL',...'ABCDEFGHIJKLMNOPQRSTUVWXYZ','#']){const b=document.createElement('button');b.textContent=value;b.className=value==='ALL'?'active':'';b.setAttribute('aria-pressed',String(value==='ALL'));b.onclick=()=>{letter=value==='ALL'?'':value;for(const other of $('alphabet').children){other.classList.toggle('active',other===b);other.setAttribute('aria-pressed',String(other===b))}render()};$('alphabet').append(b)}
function save(){try{localStorage.setItem('savepoint-stash',JSON.stringify(stash))}catch{}$('count').textContent=stash.length}
function render(){const state=Object.fromEntries(['search','genre','decade','console','rating','sort'].map(k=>[k,$(k).value]));const filtered=filterCatalog(items,{...state,letter});$('result-count').textContent=`${filtered.length} ${items===samples?'sample entries':'games'} / ${items.length} total`;$('games').replaceChildren();for(const item of filtered){const card=document.createElement('article');card.className='card';const cover=document.createElement('div');cover.className='cover';cover.style.setProperty('--color',item.color||'#6956cc');const badge=document.createElement('span');badge.textContent=item.sample?'FICTIONAL DEMO':'CATALOG PREVIEW';const titleArt=document.createElement('strong');titleArt.textContent=item.title;cover.append(badge,titleArt);const body=document.createElement('div');body.className='card-body';const meta=document.createElement('div');meta.className='meta';meta.textContent=item.console||'Console unverified';const title=document.createElement('h3');title.textContent=item.title;const detail=document.createElement('p');detail.textContent=`${item.year||'Year unknown'} · ${item.genre||'Genre unverified'}`;const button=document.createElement('button');button.textContent=stash.includes(item.id)?'✓ IN YOUR STASH':'+ ADD TO STASH';button.onclick=()=>{if(stash.includes(item.id))stash=stash.filter(x=>x!==item.id);else stash.push(item.id);save();render()};body.append(meta,title,detail,button);card.append(cover,body);$('games').append(card)}if(!filtered.length){const p=document.createElement('p');p.className='empty';p.textContent='No matches. Try a different filter or reset the index.';$('games').append(p)}save()}
for(const field of ['search','genre','decade','console','rating','sort'])$(field).addEventListener('input',render);
$('reset').onclick=()=>{for(const f of ['search','genre','decade','console','rating'])$(f).value='';$('sort').value='az';$('alphabet').firstChild.click()};
$('close').onclick=()=>$('modal').close();
$('shipping').onclick=()=>{$('modal-content').innerHTML='<p class="eyebrow">DELIVERY / USPS</p><h2>Next stop: your collection.</h2><p>This demo does not request live shipping quotes or create shipments.</p><h3>United States</h3><p>USPS service options and pricing will depend on the destination, packed weight, dimensions and eligibility.</p><h3>International</h3><p>Available destinations, customs details and service eligibility must be confirmed before a quote can be provided.</p><p>Shipping and taxes are not included. No delivery date or postage price is promised in this preview.</p>';$('modal').showModal()};
$('stash').onclick=showStash;
function showStash(){const content=$('modal-content');content.replaceChildren();const h=document.createElement('h2');h.textContent='Your save slot.';const p=document.createElement('p');p.textContent='Saved on this device. This selection is not an order or reservation. Sample items are fictional; prices, shipping and taxes are unavailable.';content.append(h,p);if(!stash.length){const empty=document.createElement('p');empty.textContent='Your stash is empty. Find something in the index.';content.append(empty)}for(const id of stash){const item=items.find(x=>x.id===id);const row=document.createElement('div');row.className='stash-row';const label=document.createElement('span');label.textContent=item.title;const remove=document.createElement('button');remove.textContent='Remove';remove.setAttribute('aria-label',`Remove ${item.title}`);remove.onclick=()=>{stash=stash.filter(x=>x!==id);save();render();showStash()};row.append(label,remove);content.append(row)}if(stash.length){const download=document.createElement('button');download.textContent='Download selection';download.onclick=()=>{const blob=new Blob(['SAVEPOINT GAMING — DEMO SELECTION\nNot an order. Prices and shipping unavailable.\n\n'+stash.map(id=>{const x=items.find(x=>x.id===id);return `${x.sample?'[FICTIONAL SAMPLE] ':''}${x.title} | ${x.console}`}).join('\n')],{type:'text/plain'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='savepoint-selection.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};content.append(download)}if(!$('modal').open)$('modal').showModal()}
render();
